name: integration test
on:
  - pull_request

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kubernetes-version: ["v1.23.12", "v1.24.6", "v1.25.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
        with:
          node_image: kindest/node:${{ matrix.kubernetes-version }}
          cluster_name: training-operator-cluster
          kubectl_version: ${{ matrix.kubernetes-version }}

      - name: Build training-operator
        run: |
          ./scripts/gha/build-image.sh
        env:
          TRAINING_CI_IMAGE: kubeflowtraining/training-operator:test
    
      - name: Deploy training operator
        run: |
          ./scripts/gha/setup-training-operator.sh
        env:
          KIND_CLUSTER: training-operator-cluster
          TRAINING_CI_IMAGE: kubeflowtraining/training-operator:test

      - name: Run tests
        run: |
          pip install pytest
          python3 -m pip install -e sdk/python; pytest sdk/python/test --log-cli-level=info
